name: slidesync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  custom_widgets_toolkit: ^0.0.76
  iconsax_flutter: ^1.0.0
  flutter_animate: ^4.5.2
  # heroine: ^0.4.0
  # marquee: ^2.3.0
  # wave: ^0.2.2
  lottie: ^3.3.1
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  stacked_card_carousel: ^0.0.4
  go_router: ^16.2.4
  another_flushbar: ^1.12.32


  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5


  google_sign_in: ^7.2.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.1.0
  firebase_database: ^12.0.0
  firebase_storage: ^13.0.0
  

  open_filex: ^4.7.0
  # permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  archive: ^4.0.7
  share_plus: ^12.0.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  path: ^1.9.1
  cached_network_image: ^3.4.1

  collection: any
  flutter_image_compress: ^2.3.0

  # External Git package
  material_shapes:
    git:
      url: https://github.com/ksokolovskyi/material_shapes.git

      
  intl: any
  crypto: ^3.0.6
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  skeletonizer: ^2.1.0+1
  
  
  infinite_scroll_pagination: ^5.1.1
  # any_link_preview: ^3.0.3
  flutter_link_previewer: ^4.1.2
  super_clipboard: ^0.9.1
  # firebase_ai: ^3.2.0
  flutter_dotenv: ^6.0.0
  pdfrx: ^2.2.4
  dotted_border: ^3.1.0
  screenshot: ^3.0.0
  flutter_chat_ui: ^2.9.0
  flutter_streaming_text_markdown: ^1.3.2
  flutter_chat_core: ^2.8.0
  window_manager: ^0.5.1
  
  xxh3: ^1.2.0
  markdown_widget: ^2.3.2+8
  # saf: ^1.0.4
  mime: ^2.0.0
  saf_stream: ^0.12.3
  saf_util: ^0.11.0
  url_launcher: ^6.3.2
  pasteboard: ^0.4.0
  super_drag_and_drop: ^0.9.1
  receive_sharing_intent: ^1.8.1
  flutter_math_fork: ^0.7.4
  google_generative_ai: ^0.4.7
  
  web_smooth_scroll: ^2.0.0
  gradient_glow_border: ^1.0.3
  es_compression: ^2.0.15

flutter_native_splash:
  android: true
  ios: true

  color: "#FCFAFE"
  image: "assets/logo/splash.png"
  color_dark: "#0B0B10"
  image_dark: "assets/logo/splash.png"

  android_12:
    color: "#FCFAFE"
    image: "assets/logo/splash.png"
    color_dark: "#0B0B10"
    image_dark: "assets/logo/splash.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/ic_foreground.png"
  android_adaptive_icon:
    # background_color: "#5000B8"
    foreground_image: "assets/logo/ic_background.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/logo/splash.png"
    icon_size: 48

msix_config:
  display_name: SlideSync
  publisher_display_name: Okikiola
  identity_name: com.bubble.slidesync
  msix_version: 1.0.0.0
  logo_path: assets/logo/logo.png
  capabilities: 'internetClient,runFullTrust'


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0
  # riverpod_lint: ^2.6.5

  isar_generator: ^3.1.0+1
  build_runner: any
  msix: ^3.16.12


dependency_overrides:
  analyzer: ^6.4.1
  dart_style: ^2.3.2



flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/animated_jsons/
    - assets/images/
    - assets/logo/
    - .env

  #-FONTS
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic

